# Generated by Django 3.2.5 on 2021-12-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_updates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('shortDesc', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('categories', models.TextField()),
                ('sku', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('images1', models.ImageField(upload_to='media')),
                ('images2', models.ImageField(upload_to='media')),
                ('images3', models.ImageField(upload_to='media')),
                ('images4', models.ImageField(upload_to='media')),
                ('images5', models.ImageField(upload_to='media')),
            ],
        ),
    ]
