# Generated by Django 3.2.5 on 2021-12-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_updates', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
