# Generated by Django 3.2.5 on 2021-12-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_updates', '0003_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
