# Generated by Django 3.2.5 on 2021-12-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_updates', '0004_auto_20211209_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addres',
            new_name='Address',
        ),
    ]
