# Generated by Django 3.2.7 on 2022-02-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_updates', '0006_address_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_title', models.CharField(default='NorthFoxGroup', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('pub_date', models.DateField()),
                ('main_content', models.CharField(default='', max_length=50000)),
                ('heading', models.CharField(default='', max_length=500)),
                ('content_heading', models.CharField(default='', max_length=500)),
                ('sub_heading', models.CharField(default='', max_length=500)),
                ('sub_content_heading', models.CharField(default='', max_length=500)),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
