# Generated by Django 3.2.7 on 2022-02-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_updates', '0008_cart_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
