# Generated by Django 3.0 on 2022-02-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_updates', '0013_auto_20220206_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='COD', max_length=15),
        ),
    ]
