# Generated by Django 3.0 on 2022-02-07 09:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('t_updates', '0015_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_Items',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=jsonfield.fields.JSONField(),
        ),
    ]
