# Generated by Django 3.0 on 2022-02-07 09:21

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('t_updates', '0016_auto_20220207_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_Length',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
