# Generated by Django 3.0 on 2022-02-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_updates', '0018_auto_20220207_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(default=9033717372, max_length=10),
            preserve_default=False,
        ),
    ]
