# Generated by Django 3.0 on 2022-02-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_updates', '0020_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
